import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  public data: any;
  public columnTitles: string[];
  public filterTerm: string;
  public resetFilterTerm: boolean;
  public isGridView: boolean;

  constructor() {
    this.data = [
      {
        'id': 1,
        'first_name': 'Cherida',
        'last_name': 'Ilieve',
        'email': 'cilieve0@pcworld.com',
        'gender': 'Female',
        'ip_address': '241.221.181.1'
      }, {
        'id': 2,
        'first_name': 'Giorgia',
        'last_name': 'Greenwood',
        'email': 'ggreenwood1@arizona.edu',
        'gender': 'Female',
        'ip_address': '71.218.22.216'
      }, {
        'id': 3,
        'first_name': 'Cristabel',
        'last_name': 'Kemmet',
        'email': 'ckemmet2@example.com',
        'gender': 'Female',
        'ip_address': '236.114.23.198'
      }, {
        'id': 4,
        'first_name': 'Rolland',
        'last_name': 'Vanne',
        'email': 'rvanne3@amazon.co.jp',
        'gender': 'Male',
        'ip_address': '209.93.120.141'
      }, {
        'id': 5,
        'first_name': 'Georgia',
        'last_name': 'Ramard',
        'email': 'gramard4@princeton.edu',
        'gender': 'Female',
        'ip_address': '79.159.11.157'
      }, {
        'id': 6,
        'first_name': 'Remington',
        'last_name': 'Capp',
        'email': 'rcapp5@rediff.com',
        'gender': 'Male',
        'ip_address': '77.14.70.197'
      }, {
        'id': 7,
        'first_name': 'Claiborne',
        'last_name': 'Obama',
        'email': 'cocloney6@livejournal.com',
        'gender': 'Male',
        'ip_address': '114.100.45.7'
      }, {
        'id': 8,
        'first_name': 'Verla',
        'last_name': 'Arendt',
        'email': 'varendt7@nba.com',
        'gender': 'Female',
        'ip_address': '24.216.88.70'
      }, {
        'id': 9,
        'first_name': 'Ario',
        'last_name': 'Mabee',
        'email': 'amabee8@fotki.com',
        'gender': 'Male',
        'ip_address': '48.177.105.30'
      }, {
        'id': 10,
        'first_name': 'Audra',
        'last_name': 'Tudbald',
        'email': 'atudbald9@google.nl',
        'gender': 'Female',
        'ip_address': '207.216.87.24'
      }, {
        'id': 11,
        'first_name': 'Baillie',
        'last_name': 'Maciunas',
        'email': 'bmaciunasa@chron.com',
        'gender': 'Male',
        'ip_address': '139.12.152.65'
      }, {
        'id': 12,
        'first_name': 'Ranee',
        'last_name': 'Wrey',
        'email': 'rwreyb@ftc.gov',
        'gender': 'Female',
        'ip_address': '106.183.255.219'
      }, {
        'id': 13,
        'first_name': 'Gregoor',
        'last_name': 'Tender',
        'email': 'gtenderc@utexas.edu',
        'gender': 'Male',
        'ip_address': '250.181.111.215'
      }, {
        'id': 14,
        'first_name': 'Wilbur',
        'last_name': 'Muddimer',
        'email': 'wmuddimerd@patch.com',
        'gender': 'Male',
        'ip_address': '175.224.174.193'
      }, {
        'id': 15,
        'first_name': 'Richy',
        'last_name': 'Lebell',
        'email': 'rlebelle@php.net',
        'gender': 'Male',
        'ip_address': '156.160.135.79'
      }, {
        'id': 16,
        'first_name': 'Mersey',
        'last_name': 'Dyers',
        'email': 'mdyersf@vinaora.com',
        'gender': 'Female',
        'ip_address': '157.112.54.144'
      }, {
        'id': 17,
        'first_name': 'Agneta',
        'last_name': 'Westwick',
        'email': 'awestwickg@bbb.org',
        'gender': 'Female',
        'ip_address': '203.142.45.145'
      }, {
        'id': 18,
        'first_name': 'Armand',
        'last_name': 'Delooze',
        'email': 'adeloozeh@nytimes.com',
        'gender': 'Male',
        'ip_address': '64.122.190.30'
      }, {
        'id': 19,
        'first_name': 'Julius',
        'last_name': 'Douse',
        'email': 'jdousei@imageshack.us',
        'gender': 'Male',
        'ip_address': '220.225.109.135'
      }, {
        'id': 20,
        'first_name': 'Elianora',
        'last_name': 'Mallindine',
        'email': 'emallindinej@multiply.com',
        'gender': 'Female',
        'ip_address': '74.113.251.156'
      }, {
        'id': 21,
        'first_name': 'Cord',
        'last_name': 'Bottby',
        'email': 'cbottbyk@istockphoto.com',
        'gender': 'Male',
        'ip_address': '119.199.213.38'
      }, {
        'id': 22,
        'first_name': 'Shandy',
        'last_name': 'Funnell',
        'email': 'sfunnelll@domainmarket.com',
        'gender': 'Female',
        'ip_address': '116.185.144.136'
      }, {
        'id': 23,
        'first_name': 'Rogers',
        'last_name': 'Jurgenson',
        'email': 'rjurgensonm@dagondesign.com',
        'gender': 'Male',
        'ip_address': '126.40.45.63'
      }, {
        'id': 24,
        'first_name': 'Victor',
        'last_name': 'Joskowicz',
        'email': 'vjoskowiczn@shareasale.com',
        'gender': 'Male',
        'ip_address': '165.142.123.191'
      }, {
        'id': 25,
        'first_name': 'Delmar',
        'last_name': 'Hamlyn',
        'email': 'dhamlyno@chronoengine.com',
        'gender': 'Male',
        'ip_address': '122.108.106.140'
      }, {
        'id': 26,
        'first_name': 'Gill',
        'last_name': 'Worsnup',
        'email': 'gworsnupp@ycombinator.com',
        'gender': 'Male',
        'ip_address': '224.164.23.218'
      }, {
        'id': 27,
        'first_name': 'Antons',
        'last_name': 'Copley',
        'email': 'acopleyq@wordpress.com',
        'gender': 'Male',
        'ip_address': '158.243.49.164'
      }, {
        'id': 28,
        'first_name': 'Web',
        'last_name': 'Deppen',
        'email': 'wdeppenr@shutterfly.com',
        'gender': 'Male',
        'ip_address': '132.94.85.27'
      }, {
        'id': 29,
        'first_name': 'Ora',
        'last_name': 'Mallalieu',
        'email': 'omallalieus@flavors.me',
        'gender': 'Female',
        'ip_address': '60.220.217.147'
      }, {
        'id': 30,
        'first_name': 'Cleo',
        'last_name': 'Klimczak',
        'email': 'cklimczakt@miibeian.gov.cn',
        'gender': 'Female',
        'ip_address': '136.248.205.245'
      }, {
        'id': 31,
        'first_name': 'Guinevere',
        'last_name': 'Durbin',
        'email': 'gdurbinu@dagondesign.com',
        'gender': 'Female',
        'ip_address': '138.239.39.209'
      }, {
        'id': 32,
        'first_name': 'Bev',
        'last_name': 'Milligan',
        'email': 'bmilliganv@icq.com',
        'gender': 'Male',
        'ip_address': '67.38.234.138'
      }, {
        'id': 33,
        'first_name': 'Kilian',
        'last_name': 'Reichert',
        'email': 'kreichertw@qq.com',
        'gender': 'Male',
        'ip_address': '112.48.51.94'
      }, {
        'id': 34,
        'first_name': 'Ranee',
        'last_name': 'Anwell',
        'email': 'ranwellx@springer.com',
        'gender': 'Female',
        'ip_address': '223.238.113.153'
      }, {
        'id': 35,
        'first_name': 'Terza',
        'last_name': 'Largan',
        'email': 'tlargany@w3.org',
        'gender': 'Female',
        'ip_address': '214.234.221.207'
      }, {
        'id': 36,
        'first_name': 'Roddy',
        'last_name': 'Haythornthwaite',
        'email': 'rhaythornthwaitez@trellian.com',
        'gender': 'Male',
        'ip_address': '95.180.232.102'
      }, {
        'id': 37,
        'first_name': 'Gayler',
        'last_name': 'Geill',
        'email': 'ggeill10@japanpost.jp',
        'gender': 'Male',
        'ip_address': '27.14.228.110'
      }, {
        'id': 38,
        'first_name': 'Ingeberg',
        'last_name': 'Ormond',
        'email': 'iormond11@blogspot.com',
        'gender': 'Female',
        'ip_address': '245.58.9.62'
      }, {
        'id': 39,
        'first_name': 'Alastair',
        'last_name': 'Raff',
        'email': 'araff12@nps.gov',
        'gender': 'Male',
        'ip_address': '255.28.124.138'
      }, {
        'id': 40,
        'first_name': 'Lincoln',
        'last_name': 'Glauber',
        'email': 'lglauber13@netlog.com',
        'gender': 'Male',
        'ip_address': '74.83.69.198'
      }, {
        'id': 41,
        'first_name': 'Norman',
        'last_name': 'Humble',
        'email': 'nhumble14@cnn.com',
        'gender': 'Male',
        'ip_address': '89.96.66.94'
      }, {
        'id': 42,
        'first_name': 'Forrest',
        'last_name': 'Crabtree',
        'email': 'fcrabtree15@ezinearticles.com',
        'gender': 'Male',
        'ip_address': '111.8.205.186'
      }, {
        'id': 43,
        'first_name': 'Estevan',
        'last_name': 'Bezarra',
        'email': 'ebezarra16@kickstarter.com',
        'gender': 'Male',
        'ip_address': '34.229.14.181'
      }, {
        'id': 44,
        'first_name': 'Agretha',
        'last_name': 'Rushford',
        'email': 'arushford17@eepurl.com',
        'gender': 'Female',
        'ip_address': '215.6.232.124'
      }, {
        'id': 45,
        'first_name': 'Josias',
        'last_name': 'Noell',
        'email': 'jnoell18@networksolutions.com',
        'gender': 'Male',
        'ip_address': '104.148.248.240'
      }, {
        'id': 46,
        'first_name': 'Irma',
        'last_name': 'Kiellor',
        'email': 'ikiellor19@dailymotion.com',
        'gender': 'Female',
        'ip_address': '160.149.221.107'
      }, {
        'id': 47,
        'first_name': 'Alberik',
        'last_name': 'Quail',
        'email': 'aquail1a@economist.com',
        'gender': 'Male',
        'ip_address': '253.219.60.138'
      }, {
        'id': 48,
        'first_name': 'Dalis',
        'last_name': 'Petche',
        'email': 'dpetche1b@drupal.org',
        'gender': 'Male',
        'ip_address': '180.30.193.95'
      }, {
        'id': 49,
        'first_name': 'Susanetta',
        'last_name': 'Halle',
        'email': 'shalle1c@ebay.co.uk',
        'gender': 'Female',
        'ip_address': '217.43.124.69'
      }, {
        'id': 50,
        'first_name': 'Gregory',
        'last_name': 'Clack',
        'email': 'gclack1d@wikispaces.com',
        'gender': 'Male',
        'ip_address': '108.101.202.244'
      }, {
        'id': 51,
        'first_name': 'Ezequiel',
        'last_name': 'Bygrove',
        'email': 'ebygrove1e@ox.ac.uk',
        'gender': 'Male',
        'ip_address': '151.125.164.77'
      }, {
        'id': 52,
        'first_name': 'Honor',
        'last_name': 'Murrells',
        'email': 'hmurrells1f@mediafire.com',
        'gender': 'Female',
        'ip_address': '202.166.0.111'
      }, {
        'id': 53,
        'first_name': 'Wayne',
        'last_name': 'Blitzer',
        'email': 'wblitzer1g@behance.net',
        'gender': 'Male',
        'ip_address': '22.73.174.236'
      }, {
        'id': 54,
        'first_name': 'Elbertina',
        'last_name': 'Le Brom',
        'email': 'elebrom1h@xing.com',
        'gender': 'Female',
        'ip_address': '71.25.169.86'
      }, {
        'id': 55,
        'first_name': 'Carling',
        'last_name': 'Pelosi',
        'email': 'cpelosi1i@chron.com',
        'gender': 'Male',
        'ip_address': '165.134.195.108'
      }, {
        'id': 56,
        'first_name': 'Romonda',
        'last_name': 'Maevela',
        'email': 'rmaevela1j@amazon.com',
        'gender': 'Female',
        'ip_address': '44.74.60.194'
      }, {
        'id': 57,
        'first_name': 'Itch',
        'last_name': 'Martugin',
        'email': 'imartugin1k@ox.ac.uk',
        'gender': 'Male',
        'ip_address': '33.232.254.176'
      }, {
        'id': 58,
        'first_name': 'Jerrold',
        'last_name': 'Filippazzo',
        'email': 'jfilippazzo1l@trellian.com',
        'gender': 'Male',
        'ip_address': '112.19.135.14'
      }, {
        'id': 59,
        'first_name': 'Tremaine',
        'last_name': 'Pembridge',
        'email': 'tpembridge1m@apple.com',
        'gender': 'Male',
        'ip_address': '251.141.79.153'
      }, {
        'id': 60,
        'first_name': 'Angela',
        'last_name': 'Wagon',
        'email': 'awagon1n@loc.gov',
        'gender': 'Female',
        'ip_address': '70.65.106.132'
      }, {
        'id': 61,
        'first_name': 'Lurette',
        'last_name': 'Genty',
        'email': 'lgenty1o@mysql.com',
        'gender': 'Female',
        'ip_address': '234.218.166.59'
      }, {
        'id': 62,
        'first_name': 'Letty',
        'last_name': 'Shade',
        'email': 'lshade1p@oracle.com',
        'gender': 'Female',
        'ip_address': '247.32.14.191'
      }, {
        'id': 63,
        'first_name': 'Iggie',
        'last_name': 'Struss',
        'email': 'istruss1q@pbs.org',
        'gender': 'Male',
        'ip_address': '5.58.115.129'
      }, {
        'id': 64,
        'first_name': 'Kinny',
        'last_name': 'Asp',
        'email': 'kasp1r@wix.com',
        'gender': 'Male',
        'ip_address': '51.100.130.109'
      }, {
        'id': 65,
        'first_name': 'Daron',
        'last_name': 'Omalka',
        'email': 'dodogherty1s@google.fr',
        'gender': 'Female',
        'ip_address': '5.203.187.60'
      }, {
        'id': 66,
        'first_name': 'Vladamir',
        'last_name': 'Gavrielli',
        'email': 'vgavrielli1t@blogspot.com',
        'gender': 'Male',
        'ip_address': '123.89.252.141'
      }, {
        'id': 67,
        'first_name': 'Winnifred',
        'last_name': 'Spera',
        'email': 'wspera1u@home.pl',
        'gender': 'Female',
        'ip_address': '95.243.61.183'
      }, {
        'id': 68,
        'first_name': 'Tris',
        'last_name': 'Pawnsford',
        'email': 'tpawnsford1v@ask.com',
        'gender': 'Male',
        'ip_address': '145.6.233.129'
      }, {
        'id': 69,
        'first_name': 'Odelle',
        'last_name': 'Andrieu',
        'email': 'oandrieu1w@printfriendly.com',
        'gender': 'Female',
        'ip_address': '35.55.203.29'
      }, {
        'id': 70,
        'first_name': 'Kaiser',
        'last_name': 'Lambswood',
        'email': 'klambswood1x@google.co.jp',
        'gender': 'Male',
        'ip_address': '236.226.214.101'
      }, {
        'id': 71,
        'first_name': 'Cull',
        'last_name': 'Comley',
        'email': 'ccomley1y@buzzfeed.com',
        'gender': 'Male',
        'ip_address': '180.17.156.9'
      }, {
        'id': 72,
        'first_name': 'Cinnamon',
        'last_name': 'Bolter',
        'email': 'cbolter1z@stumbleupon.com',
        'gender': 'Female',
        'ip_address': '35.22.88.193'
      }, {
        'id': 73,
        'first_name': 'Petr',
        'last_name': 'Smalman',
        'email': 'psmalman20@who.int',
        'gender': 'Male',
        'ip_address': '104.157.45.150'
      }, {
        'id': 74,
        'first_name': 'Pierre',
        'last_name': 'Keppe',
        'email': 'pkeppe21@netlog.com',
        'gender': 'Male',
        'ip_address': '29.12.87.97'
      }, {
        'id': 75,
        'first_name': 'Trueman',
        'last_name': 'Galpen',
        'email': 'tgalpen22@furl.net',
        'gender': 'Male',
        'ip_address': '77.134.54.241'
      }, {
        'id': 76,
        'first_name': 'Britt',
        'last_name': 'Lower',
        'email': 'blower23@godaddy.com',
        'gender': 'Male',
        'ip_address': '12.26.21.100'
      }, {
        'id': 77,
        'first_name': 'Way',
        'last_name': 'Clemence',
        'email': 'wclemence24@europa.eu',
        'gender': 'Male',
        'ip_address': '197.39.216.202'
      }, {
        'id': 78,
        'first_name': 'Abbye',
        'last_name': 'Chesnay',
        'email': 'achesnay25@discuz.net',
        'gender': 'Female',
        'ip_address': '62.170.133.99'
      }, {
        'id': 79,
        'first_name': 'Shel',
        'last_name': 'Issacof',
        'email': 'sissacof26@sina.com.cn',
        'gender': 'Female',
        'ip_address': '121.30.60.73'
      }, {
        'id': 80,
        'first_name': 'Christopher',
        'last_name': 'Tomaszewski',
        'email': 'ctomaszewski27@netscape.com',
        'gender': 'Male',
        'ip_address': '98.42.9.176'
      }, {
        'id': 81,
        'first_name': 'Marena',
        'last_name': 'Goodinge',
        'email': 'mgoodinge28@meetup.com',
        'gender': 'Female',
        'ip_address': '138.43.224.71'
      }, {
        'id': 82,
        'first_name': 'Olwen',
        'last_name': 'de Mendoza',
        'email': 'odemendoza29@tinypic.com',
        'gender': 'Female',
        'ip_address': '195.149.49.82'
      }, {
        'id': 83,
        'first_name': 'Thea',
        'last_name': 'Wroath',
        'email': 'twroath2a@simplemachines.org',
        'gender': 'Female',
        'ip_address': '30.70.67.254'
      }, {
        'id': 84,
        'first_name': 'Wright',
        'last_name': 'Seivwright',
        'email': 'wseivwright2b@theatlantic.com',
        'gender': 'Male',
        'ip_address': '183.39.87.199'
      }, {
        'id': 85,
        'first_name': 'Kinnie',
        'last_name': 'Bernardoni',
        'email': 'kbernardoni2c@si.edu',
        'gender': 'Male',
        'ip_address': '169.152.3.126'
      }, {
        'id': 86,
        'first_name': 'Reinwald',
        'last_name': 'Omindu',
        'email': 'rolynn2d@hibu.com',
        'gender': 'Male',
        'ip_address': '215.151.33.183'
      }, {
        'id': 87,
        'first_name': 'Theresa',
        'last_name': 'Volleth',
        'email': 'tvolleth2e@shinystat.com',
        'gender': 'Female',
        'ip_address': '141.113.192.130'
      }, {
        'id': 88,
        'first_name': 'Amelita',
        'last_name': 'Valiant',
        'email': 'avaliant2f@creativecommons.org',
        'gender': 'Female',
        'ip_address': '175.104.141.34'
      }, {
        'id': 89,
        'first_name': 'Gwenni',
        'last_name': 'Gaudon',
        'email': 'ggaudon2g@pagesperso-orange.fr',
        'gender': 'Female',
        'ip_address': '74.220.225.153'
      }, {
        'id': 90,
        'first_name': 'Kyle',
        'last_name': 'Erratt',
        'email': 'kerratt2h@redcross.org',
        'gender': 'Female',
        'ip_address': '54.226.210.155'
      }, {
        'id': 91,
        'first_name': 'Linn',
        'last_name': 'Kahane',
        'email': 'lkahane2i@vimeo.com',
        'gender': 'Male',
        'ip_address': '135.18.101.43'
      }, {
        'id': 92,
        'first_name': 'Pierrette',
        'last_name': 'Filyukov',
        'email': 'pfilyukov2j@zdnet.com',
        'gender': 'Female',
        'ip_address': '54.173.120.213'
      }, {
        'id': 93,
        'first_name': 'Rossy',
        'last_name': 'Stote',
        'email': 'rstote2k@icq.com',
        'gender': 'Male',
        'ip_address': '70.94.0.69'
      }, {
        'id': 94,
        'first_name': 'Ethelred',
        'last_name': 'Bocken',
        'email': 'ebocken2l@economist.com',
        'gender': 'Male',
        'ip_address': '29.118.136.38'
      }, {
        'id': 95,
        'first_name': 'Ana',
        'last_name': 'Guidi',
        'email': 'aguidi2m@netvibes.com',
        'gender': 'Female',
        'ip_address': '151.92.156.96'
      }, {
        'id': 96,
        'first_name': 'Yorke',
        'last_name': 'Draisey',
        'email': 'ydraisey2n@t.co',
        'gender': 'Male',
        'ip_address': '209.146.22.61'
      }, {
        'id': 97,
        'first_name': 'Nappy',
        'last_name': 'Farre',
        'email': 'nfarre2o@rediff.com',
        'gender': 'Male',
        'ip_address': '155.130.172.45'
      }, {
        'id': 98,
        'first_name': 'Arthur',
        'last_name': 'Alderson',
        'email': 'aalderson2p@etsy.com',
        'gender': 'Male',
        'ip_address': '103.225.77.111'
      }, {
        'id': 99,
        'first_name': 'Amil',
        'last_name': 'Harfoot',
        'email': 'aharfoot2q@purevolume.com',
        'gender': 'Female',
        'ip_address': '82.73.179.198'
      }, {
        'id': 100,
        'first_name': 'Mariam',
        'last_name': 'Flint',
        'email': 'mflint2r@thetimes.co.uk',
        'gender': 'Female',
        'ip_address': '119.177.129.101'
      }];
    this.columnTitles = ['ID', 'First name', 'Last name', 'Email', 'Gender', 'IP address'];
    this.filterTerm = '';
    this.resetFilterTerm = false;
    this.isGridView = false;
  }

  /**
   * Get filter term from the filter component.
   * @param filterTerm
   */
  public getFilterTerm(filterTerm: string): void {
    this.filterTerm = filterTerm;
    this.resetFilterTerm = false;
  }

  /**
   * Get selected data from the grid.
   * @param data - data from the grid.
   */
  public getSelectedItems(data: any): void {
    console.log(data);
  }

}
